### ISSUE TITLE
Write user stories from SOW statements (Unmesha)

### ISSUE THREAD

**Issue by Naga-Chinta** [Unmesha-SE/smarter-university-system#71]
This activity revolves around writing user stories from SOW, this is an important step in the process of software development. The team can ensure that all the required functionalities and features are delivered by writing user stories from SOW.
This activity belongs to epic #6

**Comment by Unmesha-SE** [comment]
Possible user stories :

Under Class management:
a) As a student, I should know the location of the class so that I can prepare my travel accordingly
b) As a student, I should know the number of students enrolled so far so that I can decide whether I can enroll or not
c) As an admin, I should know the course strength so that I can admit new students/drop existing ones
d) As a student, I should the sections available for a course so that I can select an appropriate time for my course
e) As an instructor, I should know the class strength so that I can prepare the lecture material and lecture mode accordingly

Under Course management:
a) As a student, I should be able to register for the courses so that I can progress towards my degree
b) As a student, I should know the prerequisites for a course so that I can request for a enrollment request if required
c) As an instructor, I should be able to view the enrollment request for a student and the prerequisites for a course so that I can determine whether the student can enroll in a course or not
d) As an administrator, I should be able to view the enrollment request for a student and the prerequisites for a course so that I can help determine whether the student can enroll in a course or not

Under Course details:
a) As a student, I should be able to view the course identifier so that I know which courses I need to register
b) As an administrator, I should be able to view the course identifier so that I do not schedule courses with conflicting times
c) As an instructor, I should be able to create/edit the syllabus so that students know what the course deals with
d) As an administrator, I should have access to instructor's information so that I can assign appropriate course to an instructor
e) As an instructor, I should be able to view the complete student list so that I can organize the class accordingly
f) As a TA, I should be able to view the complete student list so that I can help organize the class and conduct office hours/support the students
g) As an instructor/TA, I should be able to organize the students into groups for better course management
h) As an instructor/TA ,I should be able to provide/view grades for all students so that I can teach the course better/support the students
i) As a student, I should be able to view the grades so that I can gauge my progress and take necessary action to work towards my degree
