### ISSUE TITLE
Initial review/study of the activity post API endpoints (Unmesha)

### ISSUE THREAD

**Issue by Udit2399** [Unmesha-SE/smarter-university-system#80]
This activity is a crucial initial step which involves studying the possible bad requests to the system via the API endpoints. This activity will involve analyzing the possible violations to the system boundaries via API calls and defining the boundary conditions for the system to shield itself from the bad API calls.

This activity belongs to the epic #8

**Comment by Unmesha-SE** [comment]
This is my analysis for the remaining parameters
[Task 5 Analysis.docx](https://github.com/Unmesha-SE/smarter-university-system/files/13445335/Task.5.Analysis.docx)

**Comment by maria-vilanova** [comment]
This looks good, I just have a couple comments for now:

- Recipients is a list of strings, therefore the test cases should reflect that fact (probably should create new partitions related to its list attributes)
- Also, that means that Recipients needs a boundary value analysis. However I'm not sure if the max is 3 or undefined (since technically there is no limit to its size, but there are only 3 acceptable user IDs). For now let's assume the max is 3 and just ask the professor about it.
- The variable interactions test cases for Recipients should probably be reviewed and expanded as well to reflect that it is a list. I'm working on doing that for the Directed parameter, so don't worry too much about it.
- I think you can add a Latitude partition for 'no value provided'.
- For the boundary value analysis of Latitude, in the Min+ and Max+, the professor mentioned that the convention is to go up or down by 0.1 . What you have is correct but I would change them to -90.1 and 90.1 just in case.
- I believe Latitude does need test cases for interactions with the Longitude parameter. This is because for example, if only one of them is provided, or both are provided but one is invalid, both of them would then become invalid.
